# Generated by Django 3.2.9 on 2021-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='group',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512),
        ),
    ]
