# Generated by Django 3.2.9 on 2021-12-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
