# Generated by Django 3.2.9 on 2021-12-27 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_auto_20211227_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('user', 'content')},
        ),
    ]
