# Generated by Django 3.2.9 on 2021-12-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20211227_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, default='', editable=False, max_length=512),
        ),
    ]
